### ISSUE TITLE
2.B) Exfiltration Over Command and Control Channel

### ISSUE THREAD

**Issue by Cyb3rWard0g** [OTRF/detection-hackathon-apt29#4]
# Description

The file is then exfiltrated over the existing C2 connection (T1041).

`[pupy] > download "C:\Users\pbeesly\AppData\Roaming\Draft.Zip" .`

**Comment by DarthRaki** [comment]
All of my analytics are using this tool set (https://github.com/idaholab/Malcolm)

**Can I detect a C2 connection in my traffic over HTTPS**
(with such a small data its hard to show the items that stand out)

Query I start with
protocols == tls && protocols != https && tags == cert:self-signed (the driving factor behind this is if the communication is TLS encrypted but not using HTTPs it then becomes suspsect for being on ports that https would use. Add in a self-signed cert its highly likely a piece of malware)

We use SPI VIEW to quickly see all the IPs both src and dst
![https c2](https://user-images.githubusercontent.com/64702169/80891542-4d640f00-8c8a-11ea-9a8d-7f7258c4506b.PNG)

we can also see the Cert information for each item and a count next to them. (Use these items for OSINT sites like (shodan and censys.io)


We can also see the large databytes present during exfil, Timestamps also to correlate host logs
![Http c2 info](https://user-images.githubusercontent.com/64702169/80891622-cf543800-8c8a-11ea-84dd-87a98b1854dd.PNG)

**Comment by neu5ron** [comment]
yep, there are known JA3 and JA3S hashes of Kali and Metasploit.
`72a589da586844d7f0818ce684948eea`

**Comment by neu5ron** [comment]
72a589da586844d7f0818ce684948eea

althought, before people say "Nate SIGMA IS MUCH MORE THAN FOR IOC's..." yeah I know ;)

here is quick rule for sigma, I didn't grab all the JA3's in there (working on few other things), but whichever are deemed known malicious add them to the list below in the placeholders `ReplaceMeWithKnownBadJA3`



```yml
title: Known Bad JA3 Hash for attack tool
status: experimental
description: JA3 SSL/TLS hashes for known bad attack/pentesting tools
references:
    - "https://github.com/OTRF/detection-hackathon-apt29/issues/4"
author: '@neu5ron Nate Guagenti, OTRF Community'
date: 2020/05/03
modified: 2020/05/03
logsource:
    product: zeek
    service: ssl
detection:
  ja3_hashes:
   ja3:
     - '72a589da586844d7f0818ce684948eea'
     - $ReplaceMeWithKnownBadJA3
     - $ReplaceMeWithKnownBadJA3
     - $ReplaceMeWithKnownBadJA3
  condition: ja3_hash
falsepositives:
    - Always worth looking into known attack tool usage, however you may have people just trying to test a tool and it not be a full blown incident
level: medium
```
